### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chris92de** [EvoTM/EvoSC-sharp#88]
**Describe the bug**
`/kick name` fails with a stacktrace

**To Reproduce**
1. Have unrestricted user group
2. Type `/kick yourownname`
3. Get stacktrace in console and don't get kicked.

**Expected behavior**
1. Get kicked

**Screenshots**

**Server environment (please complete the following information):**
 TM2020 dedicated server version: 2022-12-14
Windows
EvoSC# version: Latest `dev` branch

**Additional context**
```
Failed to route chat message: Object reference not set to an instance of an object. | | 
Stacktrace:    
at System.Object.GetType()    
at GbxRemoteNet.GbxRemoteClient.<>c.<MethodArgs>b__75_0(Object a)    
at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()    
at System.String.Join(String separator, IEnumerable`1 values)    
at GbxRemoteNet.GbxRemoteClient.MethodArgs(Object[] args)    
at GbxRemoteNet.GbxRemoteClient.CallOrFaultAsync(String method, Object[] args)    
at GbxRemoteNet.GbxRemoteClient.KickAsync(String login, String message)    
at EvoSC.Modules.Official.Player.Services.PlayerService.KickAsync(IPlayer player, IPlayer actor) in E:\csharp-dev\EvoSC-sharp\src\Modules\Player\Services\PlayerService.cs:line 42
at EvoSC.Commands.Middleware.PermissionMiddleware.ExecuteAsync(IControllerContext context) in E:\csharp-dev\EvoSC-sharp\src\EvoSC.Commands\Middleware\PermissionMiddleware.cs:line 42
at EvoSC.Commands.Middleware.CommandsMiddleware.ExecuteCommand(IChatCommand cmd, Object[] args, ChatRouterPipelineContext routerContext) in E:\csharp-dev\EvoSC-sharp\src\EvoSC.Commands\Middleware\CommandsMiddleware.cs:line 99
at EvoSC.Commands.Middleware.CommandsMiddleware.ExecuteAsync(ChatRouterPipelineContext context) in E:\csharp-dev\EvoSC-sharp\src\EvoSC.Commands\Middleware\CommandsMiddleware.cs:line 128
at EvoSC.Common.Remote.ChatRouter.RemoteChatRouter.HandlePlayerChatRouting(Object sender, PlayerChatEventArgs e)
at EvoSC.Commands.Middleware.CommandsMiddleware.ExecuteAsync(ChatRouterPipelineContext context) in E:\csharp-dev\EvoSC-sharp\src\EvoSC.Commands\Middleware\CommandsMiddleware.cs:line 128
at EvoSC.Common.Remote.ChatRouter.RemoteChatRouter.HandlePlayerChatRouting(Object sender, PlayerChatEventArgs e)
```

**Comment by snixtho** [comment]
I believe this issue is related to GbxRemote.NET and not EvoSC#. Gonna transfer it over.
